# Generated by Django 4.1.7 on 2023-04-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_into',
            new_name='short_intro',
        ),
    ]
